### ISSUE TITLE
The system cannot find the path specified

### ISSUE THREAD

**Issue by alxtrkhv** [nikolalkc/LKC-Tools#1]
No matter how I start Reaopen.exe (from wwise or explorer) it gives me this message.
Installed/Reinstalled ReaOpen from reapack.

![image](https://user-images.githubusercontent.com/45842462/56124539-88ac7680-5f7f-11e9-812f-0d51f881518f.png)

**Comment by nikolalkc** [comment]
I'll look into it. Thanks for reporting the issue.

**Comment by nikolalkc** [comment]
Try using ReaOpen with portable version of REAPER until I inspect this issue.

**Comment by nikolalkc** [comment]
@Alxtrkhv Try now with updated version 1.75.

**Comment by alxtrkhv** [comment]
Working as expected. Thank you!
