### ISSUE TITLE
BFO & LKC - enabling creates lag/freeze in meter while playing

### ISSUE THREAD

**Issue by daeavelwyn** [nikolalkc/LKC-Tools#2]
Hello,

I love your tool letting me see if a folder has content even when it's closed, but actually, I can't use it smothlessly.

As you can see in this gif : https://imgur.com/a/LYzpeHi

1- I press play with lkc off, meters works nice
2- While a lag appears (in the middle of the animation) it's the moment I switch lkc On
3- While meters returns to normal, it's the moment I switch lkc off

Any suggestions ? workaround ?

thanks

**Comment by nikolalkc** [comment]
Hi there,

I am afraid that is not solvable. This script is cpu intensive, especially if you stack folders inside folders.
I hope that Justin will implement real folder items feature in the future releases of REAPER.

**Comment by daeavelwyn** [comment]
Arf...ok, nevermind, thanks for the reply ;)

**Comment by daeavelwyn** [comment]
Reaper Limitation.
